### PR TITLE
Protocol changes to support generating SVG images

### PR DESCRIPTION
**Pull request by lifofifoX**
These changes should make it simpler to generate collections made up of SVG images.

### CODE REVIEW

**Comment by jerryfane** [comment]
Gm, thanks for your contribution! Can you please provide and update on how the render script should change? And maybe an example on how to actually render an svg file.

Thank you!

**Comment by lifofifoX** [comment]
@jerryfane I wrote scripts to generate a random SVG and also one from an NFT inscription. That should help explain the process. Essentially, you just decode the base64 and append to a single string, save the result as an SVG file.

I hope that clarifies it!

* This script generates a random SVG file from the base inscription - https://gist.github.com/BeepsOrdinals/a1734b49f9cc79a94800ab0f95ff9079

```bash
$ ruby random_beep.rb > random.svg
```

* This script uses an example NFT inscription JSON to generate the resulting SVG - https://gist.github.com/BeepsOrdinals/e64dc89590a8372cad9b7209ba4ff37e

```bash
$ ruby generate_from_nft.rb > nft.svg
```

**Comment by lifofifoX** [comment]
I modified your inscription to render a random SVG image from my project's base inscription.

Inscription - c14e58cda85d98905c91e6d3dedd4455eb534d24aee908930044e17838d22531i0

https://www.ord.io/preview/c14e58cda85d98905c91e6d3dedd4455eb534d24aee908930044e17838d22531i0?type=text/html

I hope that clarifies it.

**Comment by jerryfane** [comment]
@BeepsOrdinals 

Thank you so much for your contribution and for explaining this to me in more detail off-gitHub. I believe your solution is a great way to extend the functionalities of GBRC721 to support types other than PNGs, and Beeps is a perfect use case for it.

In regards to your proposal, I agree that adding a 'format' key would be beneficial for renderers to understand the types of traits they are going to render. As for the 'method' key, I think we can avoid adding it for now, but we should definitely have more discussions to determine how it can be implemented in future versions. From my understanding, this addition can help make the rendering process more deterministic, as suggested by another contributor (@russanto) in https://github.com/jerryfane/generative-brc-721/issues/1. For now, we can attempt to implement a more general renderer that can be used for both PNGs and SVGs, and potentially other types in the future. Once finalized, this can be included on-chain and referenced in the 'method' key, which I propose renaming to 'renderer'. This approach will greatly assist front-ends in easily rendering GBRC721s without having to build their own solutions (which is amazing). Creators who want to have a specific renderer can still build and reference their own solution in the deploy inscription.

Regarding the last change, making 'dim' optional, it definitely makes sense with the inclusion of more types. However, I'm unsure if we should do this right now, as it may create confusion for newcomers reading the repository at this stage. Let me know what you think. In cases where types do not use 'dim,' renderers can simply ignore its value."

**Review by jerryfane — CHANGES_REQUESTED** [review]
Would you be able to also update the script to allow the generation of svgs? 
We can mention somewhere that the currently available formats by the public renderer are pngs and svgs.

**Comment by lifofifoX** [comment]
@jerryfane Fully agree on all points. I updated the PR to reflect that. So essentially, this PR is now only standardizing the `format` attribute in deploy inscription.

Re: on chain rendering, I am not fully convinced they need to be a part of the standard. Having too many ways in which a collection can be rendered, can possibly be a hinderance to adoption. So, it needs to be thought out a bit more.

**Comment by lifofifoX** [comment]
@jerryfane I'll work on updating the the script for svgs as well.

Going back to the `format` attribute, do you think it might be more useful to have it store the more standardized mime types instead? So, rather than `svg`, it could be `image/svg+xml`

**Comment by lifofifoX** [comment]
Is something like this what you have in mind?

```js
import fetch from "node-fetch";
import crypto from "crypto";

async function constructSVG(attributes, t_ins) {
    let svg = "";

    let promises = [];
    let svgComponents = new Array(attributes.length);

    for (let i = 0; i < attributes.length; i++) {
        let attribute = attributes[i];
        let inscriptionIndex = attribute[0];
        let traitValue = attribute[1];

        let traitsInscriptionId = t_ins[inscriptionIndex];

        await fetch('https://ordinals.com/content/' + traitsInscriptionId)
            .then(res => res.json())
            .then(data => {
                svgComponents[i] = atob(data.traits[data.trait_types[i]][traitValue]['base64']);
            });
    }

    // Now draw the images in order
    for (let i = 0; i < svgComponents.length; i++) {
        svg += svgComponents[i];
    }

    return svg;
}

// Parse the command-line arguments as JSON
var obj = JSON.parse(process.argv[2]);

constructSVG(obj.a, obj.t_ins).then(svg => {
    console.log(svg)

    // Compute the SHA256 hash of the SVG
    let hash = crypto.createHash('sha256');
    hash.update(Buffer.from(svg));

    console.log('*********************');
    console.log('hash:', hash.digest('hex'));
}).catch(error => {
    console.error(error);
});
```

**Comment by jerryfane** [comment]
> @jerryfane I'll work on updating the the script for svgs as well.
> 
> Going back to the `format` attribute, do you think it might be more useful to have it store the more standardized mime types instead? So, rather than `svg`, it could be `image/svg+xml`

Yes I would say using standardized mime types works better. 

Regarding the script, I had in mind something like: 

If type == png mime type then createImage() // current function we already have in the README
else if type == svg mime type then constructSVG() // the function you are proposing here. 

This should make it easier for frontend to implement standardized renderers if we propose one that works with multiple types.

**Pull request closed without merging**
